### ISSUE TITLE
Detect and reject programs consisting of multiple disjoint data flows

### ISSUE THREAD

**Issue by StephanEwen** [stratosphere/stratosphere#173]
We need to catch programs consisting of multiple disjoint data flows in the pact layer to produce a meaningful message. Otherwise the JobManager will throw a GraphConversionException at runtime, stating that the job graph is not weakly connected.

Below is are two  simple example for such a program. The first is caught by the current logic, the second is not caught in general (depends on order in which sinks are added, as that determines the way in which this graph is augmented with auxiliary nodes until it has a single root node.

<pre>
 sink        sink
   ^          ^
   |          |
source      source
</pre>

<pre>
    (SINK 3) (SINK 1)   (SINK 2) (SINK 4)
        \     /             \     /
        (SRC A)             (SRC B)
</pre>

**Comment by StephanEwen** [comment]
Fixed in 0d82ed2985dc51149629e387a1de861d631bce82

**Comment by rmetzger** [comment]
The issue is not fixed.

I have a program that does not contain a disjoint data flow, but is rejected by the compiler.

```
Exception in thread "main" eu.stratosphere.pact.compiler.CompilerException: The given Pact program contains multiple disconnected data flows.
    at eu.stratosphere.pact.compiler.plan.SinkJoiner.computeUnclosedBranchStack(SinkJoiner.java:85)
    at eu.stratosphere.pact.compiler.PactCompiler$BranchesVisitor.postVisit(PactCompiler.java:1227)
    at eu.stratosphere.pact.compiler.PactCompiler$BranchesVisitor.postVisit(PactCompiler.java:1208)
    at eu.stratosphere.pact.compiler.plan.TwoInputNode.accept(TwoInputNode.java:812)
    at eu.stratosphere.pact.compiler.plan.TwoInputNode.accept(TwoInputNode.java:810)
    at eu.stratosphere.pact.compiler.plan.TwoInputNode.accept(TwoInputNode.java:810)
    at eu.stratosphere.pact.compiler.plan.TwoInputNode.accept(TwoInputNode.java:810)
    at eu.stratosphere.pact.compiler.plan.TwoInputNode.accept(TwoInputNode.java:810)
    at eu.stratosphere.pact.compiler.plan.TwoInputNode.accept(TwoInputNode.java:810)
    at eu.stratosphere.pact.compiler.plan.TwoInputNode.accept(TwoInputNode.java:810)
    at eu.stratosphere.pact.compiler.plan.TwoInputNode.accept(TwoInputNode.java:810)
    at eu.stratosphere.pact.compiler.PactCompiler.compile(PactCompiler.java:703)
    at eu.stratosphere.pact.compiler.PactCompiler.compile(PactCompiler.java:547)
    at eu.stratosphere.pact.client.LocalExecutor.executePlan(LocalExecutor.java:80)
    at eu.stratosphere.tlabs.risk.shared.Utils.execute(Utils.java:12)
    at eu.stratosphere.tlabs.risk.usecases.CustomerAggregations.main(CustomerAggregations.java:305)
```

**Comment by StephanEwen** [comment]
Okay, it seems the checks are overly aggressive.

I will remove the check for now. Seems that we can rather live with a disjoint flow than falsely rejected plans.

**Comment by StephanEwen** [comment]
Fixed in 119a023137b1d9e22a32e35973241e49b859ce30
