### ISSUE TITLE
Deadlocks / Failed Tests on Travis-CI

### ISSUE THREAD

**Issue by rmetzger** [stratosphere/stratosphere#94]
It seems that tests are randomly failing on travis https://travis-ci.org/dimalabs/ozone.
In order to fix these issues, I'd like to document all failed tests to (hopefully) find a pattern.
Please comment if you see failed tests (with build number)

72.5 eu.stratosphere.pact.runtime.sort.AsynchonousPartialSorterITCase
69.1 eu.stratosphere.pact.test.cancelling.MatchJoinCancelingITCase
60.1 eu.stratosphere.pact.runtime.task.MatchTaskTest

```
java.util.ConcurrentModificationException
at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:819)
    at java.util.ArrayList$Itr.next(ArrayList.java:791)
    at eu.stratosphere.nephele.services.memorymanager.spi.DefaultMemoryManager.release(DefaultMemoryManager.java:336)
    at eu.stratosphere.pact.runtime.hash.BuildSecondHashMatchIterator.closuildSecondHashMatchIterator.java:105)
    at eu.stratosphere.pact.runtime.task.MatchDriver.cleanup(MatchDriver.java:173)
    at eu.stratosphere.pact.runtime.test.util.DriverTestBase.testDriver(DriverTestBase.java:190)
    at eu.stratosphere.pact.runtime.task.MatchTaskTest$5.run(MatchTaskTest.java:810)
```

56.3 eu.stratosphere.pact.test.cancelling.MatchJoinCancelingITCase
33.3 eu.stratosphere.pact.test.contracts.UnionITCase

On my travis (https://travis-ci.org/rmetzger/ozone/builds)

58.4 eu.stratosphere.pact.test.contracts.CrossITCase

**Comment by rmetzger** [comment]
It happened again (without a code change),
 93.3 https://travis-ci.org/dimalabs/ozone/jobs/11768081

```
Running eu.stratosphere.pact.runtime.task.MatchTaskTest
java.util.ConcurrentModificationException
    at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:782)
    at java.util.ArrayList$Itr.next(ArrayList.java:754)
    at eu.stratosphere.nephele.services.memorymanager.spi.DefaultMemoryManager.release(DefaultMemoryManager.java:336)
    at eu.stratosphere.pact.runtime.hash.BuildSecondHashMatchIterator.close(BuildSecondHashMatchIterator.java:105)
    at eu.stratosphere.pact.runtime.task.MatchDriver.cleanup(MatchDriver.java:173)
    at eu.stratosphere.pact.runtime.test.util.DriverTestBase.testDriver(DriverTestBase.java:190)
    at eu.stratosphere.pact.runtime.task.MatchTaskTest$5.run(MatchTaskTest.java:810)
Tests run: 23, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 7.297 sec <<< FAILURE!
```

**Comment by rmetzger** [comment]
101.6 
eu.stratosphere.nephele.services.iomanager.IOManagerITCase: No output for 10 minutes

**Comment by rmetzger** [comment]
106.1 https://travis-ci.org/dimalabs/ozone/jobs/12010811
eu.stratosphere.pact.runtime.task.chaining.ChainTaskTest

**Comment by rmetzger** [comment]
124.2 https://travis-ci.org/dimalabs/ozone/jobs/12317633
Running eu.stratosphere.pact.runtime.task.MatchTaskTest
java.util.ConcurrentModificationException

This is the third time for the `MatchTaskTest`. So I think we need to investigate this!

**Comment by rmetzger** [comment]
131.4
MatchTaskTest: https://s3.amazonaws.com/archive.travis-ci.org/jobs/12381122/log.txt

**Comment by StephanEwen** [comment]
The source of the problems seems to be the following: The hash iterator code performs the following on close:
1. Close the hash table
2. Release the memory

While the hash table checks if it was closed before (even if not atomically), the memory release may be attempted multiple times concurrently. The treatment of the segments themselves is guarded by the memory manager's lock, but the iterator is created outside, leading to concurrent modifications on the collection of memroy segments to be released.

A fix would be to move the iterator instantiation in 
  eu.stratosphere.nephele.services.memorymanager.spi.DefaultMemoryManager line 321 into the critical section.

Should have no performance impact.

**Comment by StephanEwen** [comment]
Looking at the memory manager code, there is quite a bit of bookkeeping done. Especially maintaining a set of all memory segments per task is intensive, unless it is bulk released. At the moment, each segment is individually added and removed form/to a hash set.

We may want to reduce this at some point, as it will impact large memory setups. Especially when operators are initialized multiple times, such as in the iterative setups.

**Comment by StephanEwen** [comment]
Here is a quick fix for one possible scenario.

https://github.com/StephanEwen/ozone/commit/a33e1a39a15f5360a2ae671e682108ff61dc024a

This is only a quick fix to reduce odds of problems. I think most components have potential concurrency issues when close()/release() is called multiple times concurrently. This could be an issue for clean canceling/failing. A really clean approach would require either an atomic close flag in the components that are cancelled/closed to make sure that the call is processed only once.

Read accesses during regular working stay unsynchronized. We generally assume that when data structures are asynchronously destroyed, it is due to abort/cancel calls. The regular worker threads that have not yet picked up the cancelled status are okay with terminating due to an exception. Given that the operator status is set to "cancelled", any exceptions in the worker threads are discarded as side effects of asynchronous cancelling.

**Comment by StephanEwen** [comment]
Fixed in 7b0c53b4c501690866523468f6c3e7f06438658c

**Comment by rmetzger** [comment]
Bug not fixed: https://travis-ci.org/stratosphere/stratosphere/jobs/15221967

**Comment by StephanEwen** [comment]
java.util.ConcurrentModificationException
    at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:819)
    at java.util.ArrayList$Itr.next(ArrayList.java:791)
    at eu.stratosphere.nephele.services.memorymanager.spi.DefaultMemoryManager.release(DefaultMemoryManager.java:336)
    at eu.stratosphere.pact.runtime.hash.BuildFirstHashMatchIterator.closuildFirstHashMatchIterator.java:96)
    at eu.stratosphere.pact.runtime.task.MatchDriver.cleanup(MatchDriver.java:151)
    at eu.stratosphere.pact.runtime.test.util.DriverTestBase.testDriver(DriverTestBase.java:190)
    at eu.stratosphere.pact.runtime.task.MatchTaskTest$4.run(MatchTaskTest.java:766)
Tests run: 24, Failures: 2, Errors: 0, Skipped: 0, Time elapsed: 7.494 sec <<< FAILURE!

Failed tests: 
  testCancelHashMatchTaskWhileBuildFirst(eu.stratosphere.pact.runtime.task.MatchTaskTest)
  testCancelHashMatchTaskWhileBuildFirst(eu.stratosphere.pact.runtime.task.MatchTaskTest)

**Comment by StephanEwen** [comment]
The concurrent modification exception has been fixed.

Sometimes, I/O heavy tasks time out. I guess that is a VM issue, as it happens only sometimes and has never been observed by anyone on his/her local machine. I think we need to accept that some tests time out once in a while.
